services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.6.3.64
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'

  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-16T23-46-41Z
    container_name: minio
    hostname: minio
    command: server --address 0.0.0.0:10000 --console-address 0.0.0.0:10001 /data
    ports:
      - '127.0.0.1:10000:10000'
      - '127.0.0.1:10001:10001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio-data:
